apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "trymarqet.fullname" . }}-jwt-authz-orders
  namespace: {{ include "trymarqet.namespace" . }}
  labels:
    {{- include "trymarqet.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: orders
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["trymarqet/users"]
    to:
    - operation:
        paths: ["*"]
  - from:
    - source:
        namespaces: [{{ include "trymarqet.namespace" . }}]
    to:
    - operation:
        paths: ["*"]