apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trymarqet.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trymarqet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
